[workspace]
resolver = "2"
members = [ "algebra","arithmetic", "circuit-compilers", "elliptic-curve", "statements", "utils"]

[workspace.dependencies]
anyhow = "1.0.97"
sha2 = "0.10.8"
utils = { path = "utils" }
